# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-22 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chocorate', '0002_auto_20180322_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Upload image of chocolate here', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chocolate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chocorate.Chocolate')),
            ],
        ),
    ]
