# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-22 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chocorate', '0003_post_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='postType',
        ),
    ]
