# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocorate', '0005_auto_20180322_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chocolate',
            name='avgrating',
            field=models.FloatField(default=2.5),
        ),
        migrations.AlterField(
            model_name='chocolate',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
