# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-23 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocorate', '0006_auto_20180322_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=500)),
                ('rating', models.FloatField(default=2.5)),
            ],
        ),
    ]
